1.1.0 changes
fortinet-fortisoar/widget-setup-guide pull request #4
Opened 2024-11-22 11:19 UTC by cs-abhishek-shukla

- Updated screenshots
- Added release notes
- Hid the widget version from the SS

2024-11-22 11:21 UTC, cs-suyog-jinturkar commented on docs/res/setup-guide-done.png
wrongly updated?

2024-11-22 11:21 UTC, cs-suyog-jinturkar commented on docs/res/setup-guide-expanded.png
same as abovE?

2024-11-22 11:21 UTC, cs-suyog-jinturkar commented on docs/res/setup-guide-launch-point.png
same as above

2024-11-22 11:21 UTC, cs-suyog-jinturkar commented on docs/res/setup-guide-na.png
same as above

2024-11-25 05:38 UTC, cs-abhishek-shukla commented on docs/res/setup-guide-done.png
Apart from image size, everything else seems to be in order. The version number has been grayed out, though.

2024-11-25 06:59 UTC, cs-suyog-jinturkar approved these changes

2024-11-25 06:59 UTC, cs-suyog-jinturkar commented
LGTM

2024-11-25 07:17 UTC, cs-rohit-khune requested changes

2024-11-25 07:17 UTC, cs-rohit-khune commented on release_notes.md
> +   - **Updated Launch Button**: *Configure Exclude List* is now **Configure Indicator Extraction and Exclusion**
@cs-abhishek-shukla , Please replace "Configure Indicator Extraction and Exclusion" with "Manage Indicator Exclusion List"

![image](https://github.com/user-attachments/assets/52bced2d-0345-43e6-b986-2d033eef3714)

2024-11-25 07:24 UTC, cs-rohit-khune approved these changes

2024-11-25 07:25 UTC, merged